#
# Copyright 2021 Splunk Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ARG BASE_IMAGE=localhost/doc-hub/gitbook/builder:latest
FROM ${BASE_IMAGE}

#--------------------------------------
# INSTALL NPM DEPENDENCIES
#--------------------------------------

# Copy package.json
COPY scripts/*.json /kit/scripts/
COPY app/*.json /kit/app/
COPY plugins/gitbook/*.json /kit/plugins/gitbook/
COPY plugins/gitbook/gitbook-plugin-theme-splunk/*.json \ 
  /kit/plugins/gitbook/gitbook-plugin-theme-splunk/
COPY plugins/gitbook/gitbook-plugin-splunk-highlight/*.json \ 
  /kit/plugins/gitbook/gitbook-plugin-splunk-highlight/

# Build npm dependencies
RUN echo development > /kit/SDK_VERSION && \
    cd /kit/app && npm install && \
    cd /kit/scripts && npm install && \
    cd /kit/plugins/gitbook/gitbook-plugin-theme-splunk && npm install && \
    cd /kit/plugins/gitbook/gitbook-plugin-splunk-highlight && npm install && \
    cd /kit/plugins/gitbook/ && npm install

# Copy dev script
COPY scripts/dev.js /kit/scripts/dev.js

#--------------------------------------
# Start Dev Script
#--------------------------------------
VOLUME /src

ENV PATH_WORKSHOP=/mount

ENTRYPOINT ["node", "/kit/scripts/dev.js"]